version: "3.3"
   
services:
  service_a:
    build: .
    image: observability_service:0.0.11
    container_name: service_a
    environment:
      - name=service_a
    env_file:
      - ./config/environment
    labels:
      com.datadoghq.ad.logs: '[{"type": "docker", "source": "app_container", "service": "flask_service"}]'
    # volumes:
    #   - /tmp/logs:/logs/app/
    ports:
      - "5000:5000"
  service_aa:
    build: .
    image: observability_service:0.0.11
    container_name: service_aa
    environment:
      - name=service_aa
    env_file:
      - ./config/environment
  service_ab:
    build: .
    image: observability_service:0.0.11
    container_name: service_ab
    environment:
      - name=service_ab
    env_file:
      - ./config/environment  
  service_aba:
    build: .
    image: observability_service:0.0.11
    container_name: service_aba
    environment:
      - name=service_aba
    env_file:
      - ./config/environment      
  service_abb:
    build: .
    image: observability_service:0.0.11
    container_name: service_abb
    environment:
      - name=service_abb
    env_file:
      - ./config/environment      
  service_abaa:
    build: .
    image: observability_service:0.0.11
    container_name: service_abaa
    environment:
      - name=service_abaa
    env_file:
      - ./config/environment      
  service_ac:
    build: .
    image: observability_service:0.0.11
    container_name: service_ac
    environment:
      - name=service_ac
    env_file:
      - ./config/environment      
  service_aca:
    build: .
    image: observability_service:0.0.11
    container_name: service_aca
    environment:
      - name=service_aca
    env_file:
      - ./config/environment      
  service_acb:
    build: .
    image: observability_service:0.0.11
    container_name: service_acb
    environment:
      - name=service_acb
    env_file:
      - ./config/environment      
  mail:
    image: bytemark/smtp
    restart: always
    container_name: mail
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - mail

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    depends_on:
      - alertmanager

networks:
  default:
