version: "3.9"
   
services:
  service_a:
    build: .
    image: observability_service
    container_name: service_a
    environment:
      - name=service_a
    networks:
      - docker-elk_elk
    ports:
      - "5000:5000"
  service_aa:
    build: .
    image: observability_service
    container_name: service_aa
    environment:
      - name=service_aa
    networks:
      - docker-elk_elk
  service_ab:
    build: .
    image: observability_service
    container_name: service_ab
    environment:
      - name=service_ab
    networks:
      - docker-elk_elk
  service_aba:
    build: .
    image: observability_service
    container_name: service_aba
    environment:
      - name=service_aba
    networks:
      - docker-elk_elk
  service_abb:
    build: .
    image: observability_service
    container_name: service_abb
    environment:
      - name=service_abb
    networks:
      - docker-elk_elk  
  redis_abb:
    image: redis
    command: redis-server --requirepass 1234
    container_name: redis_abb
    networks:
      - docker-elk_elk
    depends_on:
      - service_abb
  service_abaa:
    build: .
    image: observability_service
    container_name: service_abaa
    environment:
      - name=service_abaa
    networks:
      - docker-elk_elk
  service_ac:
    build: .
    image: observability_service
    container_name: service_ac
    environment:
      - name=service_ac
    networks:
      - docker-elk_elk
  service_aca:
    build: .
    image: observability_service
    container_name: service_aca
    environment:
      - name=service_aca
    networks:
      - docker-elk_elk
  service_acb:
    build: .
    image: observability_service
    container_name: service_acb
    environment:
      - name=service_acb
    networks:
      - docker-elk_elk
  # mail:
  #   image: bytemark/smtp
  #   restart: always
  #   container_name: mail
  
  # alertmanager:
  #   image: prom/alertmanager
  #   container_name: alertmanager
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #   depends_on:
  #     - mail

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
  #   depends_on:
  #     - alertmanager

networks:
  docker-elk_elk:
    external: true