scrape_configs:
  - job_name: 'node'

    scrape_interval: 1s

    static_configs:
      - targets: ['service_a:5000', 'service_aa:5000', 'service_ab:5000', 'service_ac:5000', 'service_aba:5000', 'service_abaa:5000', 'service_aca:5000', 'service_acb:5000']
        labels:
          group: 'dev'

rule_files:
  - alert.rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'